- js/interface.js
Metadata might have changed since last get them from the server.
Fixes Fliplet/fliplet-studio#1433
https://sentry.io/fliplet/widgets-interface/issues/356456919/
> Fix: Don't cache get data source

- interface.html
- js/interface.js
we forgot to remove the header from the interface, as it became part of Studio and refactor the resize function.
The user couldn't see the end of the table.
Fixes https://github.com/Fliplet/fliplet-studio/issues/2036
> Fixes #2036

- js/spreadsheet.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/2762
> Increases default copyPaste limit of 1000 rows/columns to 1 billion

- js/spreadsheet.js
Also tested opening after saving with huge rows. Table keeps its share and when editing the cell it focus and scroll to the end. No more jumping around.
> Fixes issue with jumping column width

- css/interface.css
- interface.html
- js/interface.js
- js/interface.templates.js
- templates/dataSource.interface.hbs
This enhancement is for when a user clicks on App Data from the right side bar in Edit, the overlay with the list of data sources, only shows the data sources used by the app.
Studio commit reference: https://github.com/Fliplet/fliplet-studio/pull/3386/commits/f5eb3d421e555ff0ee7d3e0e0efe95b16c008769
> Allow the data sources widget to initialise filtered by appId

- js/interface.js
- js/spreadsheet.js
This PR fixes the data source column resizing for good as follows:
- width for all columns is now retained between refreshes
- width for all columns is now stored into the database so it's retained across all users
---
refs
- https://github.com/Fliplet/fliplet-studio/issues/3839
- https://github.com/Fliplet/fliplet-studio/issues/2752
- possibly many more
> Columns width to be stored in dataSource definition

- js/interface.js
Fliplet/fliplet-studio#4036
Added trim to name, the input gets highlighted if the name is empty.
> User now cannot change data source name to empty (or only spaces), input gets highlighted

- interface.html
- js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/4868
Added prevent default on enter.
Enter does not work. Nothing to show)
This change is fully backward copmatible.
I used both event.keyCode and event.which because I read in the documentation that sometimes event.keyCode does not work in older firefox versions.
> Now pressing enter on data source name input not triggers delete modal

- js/interface.js
Fliplet/fliplet-studio#3774
Replaced default confirm with Fliplet.confirm. Added names of apps where the data source is used.
> Before deleting data source modal window will show apps where this data source is used

- js/spreadsheet.js
Fliplet/fliplet-studio#3584
Added beforePaste method which trims empty row and columns.
> When pasting into data source empty row and columns will be deleted

- js/interface.js
- js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/4864
https://github.com/Fliplet/fliplet-studio/issues/3161
Added padding column to the end of the data source so a user can resize the last cell without any trouble
To avoid any problem with saving data sources. When a user enters data into an empty column we will automatically add a column header.
> Added padding column to the end of the data source so a user can resize the last cell without any trouble

- css/interface.css
- js/interface.templates.js
- templates/dataSource.interface.hbs
Fliplet/fliplet-studio#4295
Replaced a with span. Added necessary classes.
> Now users cannot open data source in a new tab

- css/interface.css
- js/spreadsheet.js
Fliplet/fliplet-studio#2597
Fliplet/fliplet-studio#2206
Added function that adds max-height to cell according to Tonys jsfiddle. Max-height is limited to 5 lines. Also added the possibility to resize row.
> Added max-height to cells, rows are now resizable

- js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/5304
User can edit large data sources
This issue occurs because when the `handsontable` get cell data through the `getCell` method we can't get data from the cell witch was scrolled on the page. But with the help of the `getColumns` method, we get only data source headers, not specific cells.
> User can edit large data sources

- js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5306
When user is trying to delete a data source from data source overlay that is not used by any app variable 'currentDS' comes as undefined. Added extra check for it.
> User is now able to delete data source that is not used by any app from data source overlay

- js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/5319
https://github.com/Fliplet/fliplet-studio/issues/5309
Corrected behavior when trimming empty columns. Fixed call stack bug when pasting empty data or empty cell.
> User now can paste row in data source, fixed error when pasting empty data

- js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/2480
When we press ctrl + a key combination we will select only cells with data in them
> When we press ctrl + a key combination we will select only cells with data in them

- interface.html
- js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/3113
When a user selects any tab except the entries and the quit and returns to the data source again he will see the entries tab.
Fix the second loader when data source called as an overlay
Fix the second loader when data source called as an overlay
Before
After
Need to be tested on a large amount of data.
> When a user select any tab except the entries and the quit and return to the data source again he will see the entries tab

- js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5671
The issue occurred because just created data source has no apps assigned to it.
> Now user can delete just created data source

- js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5318
When user will sort data sources by the name they will be sorted correctly
https://share.getcloudapp.com/v1uD6yrZ
> When user sort data sources by the name they will be sorted correctly

- js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/5278
The column will save its width when the user deletes a column to the left of it.
https://share.getcloudapp.com/z8uxJwm1
> The column will save its width when the user deletes a column to the left of it.

- js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/5278
Saving columns width when deleting a column before. After the column was manually resized
https://share.getcloudapp.com/WnuGKDjK
The solution was taken from this [issue](https://github.com/handsontable/handsontable/issues/3386)
@upplabs-alex-levchenko @MaksymShokin
> Saving columns width when deleting column before. After column was manually resized

- js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5640
Added max size limit for data source name in 255 chars
https://share.getcloudapp.com/Jrube6K7
> [Fix] Added max size limit for data source name in 255 chars

- js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1031
Changes to the search field caused by Cut/Copy/Paste actions were not being processed. This adds an event listener to the `input` event so that all changes are correctly processed.
Debounce function is also correctly scoped for reuse.
> ID-1031 [Fix] Ensures changes in the search input are processed correctly

- js/interface.js
- js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1026
- Speeds up computation of unique column names by 4~5x https://jsbench.me/p3koki07ry/2
- Reduces Handsontable initialisation time by ~33% by avoiding a re-render right after initialisation
- Reduces time spent in custom render functions by ~50% using a more efficient wrapping function
- More accurately use column header widths
- On initial render, loads an empty Handsontable before loading data. This speeds up load time from ~160 seconds to ~5 seconds for 10k entries.
Includes changes from https://github.com/Fliplet/fliplet-widget-data-source/pull/137/commits/7072b6477915e173c4b059784a4840577238384b from [this PR](https://github.com/Fliplet/fliplet-widget-data-source/pull/137)
<details>
<summary>Before (~5 seconds)</summary>
</details> …
> ID-1026 [Maintenance] Speeds up initialization of Handsontable

- js/interface.js
@romanyosyfiv @inna-bieshulia
OD-389 https://weboo.atlassian.net/browse/OD-389
**Problem:** When opening the Data Source list through a modal window, two help links are displayed.
**Solution:** When opening the Data Source list through a modal window, a "hidden" class is added for the link near the search input to hide it.
https://storyxpress.co/video/kv846ctvs1z4mq69y
> OD-389 [Fix] Hiding one of the help links for Data source manager when opened through a modal window.

- js/spreadsheet.js
@romanyosyfiv
OD-563 https://weboo.atlassian.net/browse/OD-563
**Problem**: Scrolling was not possible because the focus on the header cell was not removed
**Solution**: Before moving to the next body cell, the focus on the header cell is turned off
https://user-images.githubusercontent.com/86256215/144256925-c0c62d5b-ddc7-48c4-a370-a648bad6a6ea.mp4
Backward compatibility
> OD-563 [Fix] Fixed scrolling to a cell after sorting

- interface.html
@romanyosyfiv
OD-638 https://weboo.atlassian.net/browse/OD-638
**Problem**: When switched tables, the width of the columns differed
**Solution**: Added static width for some columns so that tables do not differ
> OD-638 [Fix] Added static width for dataSourceTable columns

- js/interface.js
API - GET `v1/data-sources` API 
Update GET `v1/data-sources` API - add excludeTypes query param support which can accept data source type separated by comma e.g. excludeTypes=bookmarks,likes,comments,menu
[XOR-7](https://weboo.atlassian.net/browse/XOR-7)
https://user-images.githubusercontent.com/101858104/174721701-70eae059-52e5-466e-a260-934c2799db1d.mp4
None
None
None
> XOR-7 [FEAT] Ensure excludeTypes param added in datasource GET call

- interface.html
- js/interface.js
Widget Data Source -> App Data -> Select DataSource -> Security Rule -> Add/Edit security Rule -> Cancel button
In this PR we have added Cancel button for Create / Edit Security Rule dialog box. On click of Cancel button dialog box is closing.  
[click here](https://weboo.atlassian.net/browse/XOR-325)
**Result**
**Checklist**
None
None
None
None
> XOR-325 [feat] Ensure user can see Cancel button on Create/Edit Security Rule

- js/interface.js
The data source version history tab is shown when the data source contains data. However, if the data source has been cleared it doesn't show up anymore, so the user is not able to restore it when it has been wiped.
I changed the functionality so that the tab is shown at all times.
> ID-2451 [Fix] Ensure show versions button is shown when the data source is empty

- js/interface.js
Screen -> App Data -> Data Sources -> Security Rules -> Reorder Rules
Implemented fix so that width of reordering row matched with width of columns and table
[JIRA](https://weboo.atlassian.net/browse/XOR-431)
[XOR-Test-431+.webm](https://user-images.githubusercontent.com/108272606/188591043-b3ed69af-33c6-45e4-a63a-084e3487513e.webm)
none
none
none
none
> XOR-431 [Fix] Ensure DS security rules retain the correct column widths when dragging

- js/interface.js
- `interface.js` 
- Fliplet Widget - fliplet-widget-data-source ` interface.js`
- This PR changed to specify the sort order as order ASC, id ASC.
- Accept input in the request body as follow:
```
{
order: [
['order', 'ASC'],
['id', 'ASC']
]
}
```
- [XOR-563](https://weboo.atlassian.net/browse/XOR-563)
- Video recording 
https://user-images.githubusercontent.com/107605720/194559633-3fb452d3-ccf3-4713-bff5-96da784da4c3.mp4
https://user-images.githubusercontent.com/107605720/194559659-7b19c098-a133-4c28-9309-7891383da5a2.mp4
> XOR-563[FIX] Ensure create record automation copies records in the correct order
