js/interface.js
Adds support for arrays, json objects, numbers and booleans.
=> Support for data types

js/interface.js
Fliplet/fliplet-studio/issues/354
=> fixed data source columns

css/interface.css, interface.html, js/interface.js
- Adds “Save changes” button
- Makes table-entries area scrollable
- Adds floating toolbar
=> Updates to interface

js/interface.js
=> We want some numbers not to be numbers

js/interface.js
=> When fetch fails show a proper message

css/interface.css, interface.html, js/interface.js
Adds the bundle setting to the settings UI
=> Bundle setting

interface.html, js/interface.js
=> Show datasource id on settings

interface.html, js/interface.js
=> Backdoor UI

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/1530
=> refresh list on back

css/interface.css, interface.html
=> Cleanup padding

js/spreadsheet.js
Because we are using the columnSorting plugin functions we need hot first initialized to get the plugin.
=> Move columnSorting function after table init

css/interface.css, interface.html, js/interface.templates.js, templates/dataSource.interface.hbs
- ID column added for quick visibility of the data source's ID
=> Added ID column

js/spreadsheet.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/2973 and https://github.com/Fliplet/fliplet-studio/issues/3012
=> Fixes IE 11 compatibility issue

css/interface.css, interface.html
=> Corrects table border styles in data source manager

js/interface.js
Ref. https://github.com/Fliplet/fliplet-e2e-tests/issues/272
Initial error message:
If user clicks **Details**...
=> Logs and renders errors when loading data sources

js/interface.js
fixes https://github.com/Fliplet/fliplet-e2e-tests/issues/274
=> removed incorrect return

interface.html, js/interface.js, widget.json
ref https://github.com/Fliplet/fliplet-studio/issues/4322
=> added hooks editor

js/spreadsheet.js, widget.json
ref https://github.com/Fliplet/fliplet-studio/issues/5059
---
- Arrays will be displayed as CSV so they can be edited
- Cell values are converted back to arrays when saving
=> allow editing array of values

js/spreadsheet.js
Fliplet/fliplet-studio#3678
Added default value.
=> Toolbar now works even before user clicks on the data source

js/interface.js
Fliplet/fliplet-studio#3773
Changed confirm to Fliplet.Modal.confirm. Added alert when the user is trying to submit empty (only spaces) name.
=> Now user cannot create data source with empty name (spaces)

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/3841
Added a separate variable for searching.
=> Search now works correctly in data source

css/interface.css, interface.html, js/interface.js, js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/3113
Show to a user message while loading and rendering data
=> Show to a user message while loading and rendering data

js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/2480
When user select data selection will be similar to the google sheets
=> When user select data selection will be similar to the google sheets

js/interface.js
=> Error catch on commit save to display a modal

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5642
Updated modals.
=> Modals updated from default to Fliplet standart

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/3805
Data source created in the app will be linked to the app in which it was created
https://share.getcloudapp.com/d5u0nRAY
=> Data source created in the app will be linked to the app in which it was created

css/interface.css, interface.html, js/interface.js, js/interface.templates.js, templates/users.interface.hbs, templates/version.interface.hbs, templates/versions.interface.hbs
Todo (all done)
- ~UI WIP~
- ~There's a few bugs to iron out~
---
Full flow https://share.getcloudapp.com/04uKjk4R
---
=> Support for Version history

css/interface.css, interface.html, js/interface.js, js/spreadsheet.js
https://github.com/Fliplet/fliplet-studio/issues/6168
Returned old loader for the data source
https://share.getcloudapp.com/JruWrA8Z
=> Returned old loader for data source

js/interface.js
ref https://fliplet.slack.com/archives/C6BUBB5NF/p1591024283001600?thread_ts=1591022221.000800&cid=C6BUBB5NF
- Renames "Insert" to "Write"
- Cleanup based on ESLint rules
=> [Fix] Typo

js/interface.templates.js, templates/accessRule.interface.hbs
=> [Maintenance] Refactored style for toggle

interface.html, js/interface.js, js/interface.templates.js
- Copy update
- Sort apps by name
- Apply changed to have a specific button
- Confirmation message when rules are saved
=> [Maintenance] Post review fixes for acl

js/interface.js
follows https://github.com/Fliplet/fliplet-widget-data-source/pull/92
=> [Fix] fixes for tokenfield resetting values

css/interface.css, interface.html, js/interface.js, js/preconfigured-rules.js, widget.json
=> [Feat] Added preconfigured rules UI

js/interface.js
GIF https://share.getcloudapp.com/kpu5A9KW
=> [Feat] Open security rules when required by the overlay data

interface.html
Ref. https://github.com/Fliplet/fliplet-studio/issues/6953
=> [Maintenance] Adds "Admin" label to Fliplet Admin-only features

interface.html, js/interface.js, js/interface.templates.js, templates/dataSource.interface.hbs
Ref. https://weboo.atlassian.net/browse/ID-128
1. A new **Available offline** column is added to show which data sources are bundled and available offline in native apps (web apps can only access data sources online). This makes it easier to glance which data sources are bundled offline.
1. **Updated at** column is also updated to stop using the calendar format, which not only doesn't conform to different regional date formats, but also incorrectly describes the days of the week, e.g. if today is Friday and the data source is updated 2 days ago, it says "Last Wednesday" instead of just "Wednesday".
=> [Feat] Adds new column in data list to show bundled data sources

css/interface.css
Ref https://weboo.atlassian.net/browse/ID-128
Follows #98
=> [Chore] Add minimum width to some columns

css/interface.css
https://weboo.atlassian.net/browse/OD-119
Added a more precise selector for the actions dropdown.
https://share.getcloudapp.com/p9uwE6BJ
=> [Fix] OD-119 Dropdowns will be displayed correctly in all parts of the data source.

.eslintignore, .eslintrc, .gitignore, js/interface.js, js/preconfigured-rules.js, js/spreadsheet.js, js/undo-redo.js, package-lock.json, package.json
OD-235 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-235
Change need help link
=> OD-235 [Feature] Update eslint

interface.html, js/interface.js, widget.json
OD-100 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-100
Optimization for data source manager
https://screencast-o-matic.com/watch/cYXDoxLVuc
=> OD-100 [Feature] Optimization Api calls for data source manager

js/interface.js, js/spreadsheet.js
@sofiiakvasnevska
OD-351 https://weboo.atlassian.net/browse/OD-351
Remove empty columns that have the Column (X) format across the whole data source entries on save.
https://monosnap.com/file/BldXrPB5g0jN8yPIk8a7A9yIUSRV2m
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii
=> OD-351 [Feat] Remove empty columns that have the Column (X) format across the whole data source entries

css/interface.css
@sofiiakvasnevska
OD-455 https://weboo.atlassian.net/browse/OD-455
Added autocomplete scroll for exclude columns menu
https://monosnap.com/file/BIxtoonhFkVuuUxDZ35LzN0o9M6t2n
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii
=> OD-455 [Fix] Add autocomplete scroll for exclude columns menu

js/interface.js
OD-248 https://weboo.atlassian.net/browse/OD-248
- Added changes to delete data sources without refresh page
http://somup.com/crfV6Rb5lg
=> OD-248 [Fix] Remove data source from the list when it's deleted

interface.html
OD-458 https://weboo.atlassian.net/browse/OD-458
Added fixes to display last updated column
=> OD-458 [Fix] Display Last updated column

js/interface.js
OD-459 https://weboo.atlassian.net/browse/OD-459
Added fixes to sorting in data source manager
http://somup.com/crfVQfb5hD
=> OD-459 [Fix] Ensure sorting works after sorting multiple times

js/interface.js
OD-248 https://weboo.atlassian.net/browse/OD-248
Reverts Fliplet/fliplet-widget-data-source#123
=> Revert OD-248 [Fix] Remove data source from the list when it's deleted

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-891
=> ID-891 [Maintenance] Copy update

js/spreadsheet.js
@sofiiakvasnevska
OD-467 https://weboo.atlassian.net/browse/OD-467
Paste in a row without filling the full row
https://monosnap.com/file/nQMtGddJsbHwi8sqH2g6qYka5XGSIE
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii
=> OD-467 [Fix] Paste in a row without filling the full row

js/spreadsheet.js
@sofiiakvasnevska
OD-450 https://weboo.atlassian.net/browse/OD-450
Parse nested arrays and objects for render in spreadsheet correctly
https://monosnap.com/file/MdPV4ocMYAKreLFsf8fdEEEqRmJPFr
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii
=> OD-450 [Fix] Parse nested arrays and objects for render in spreadsheet correctly

css/interface.css, js/interface.js
OD-461 https://weboo.atlassian.net/browse/OD-461
Changed the message format
=> OD-461 [Feature] Change message format when permanently deleting data sources

css/interface.css, interface.html, js/interface.js
OD-468 https://weboo.atlassian.net/browse/OD-468
Added new logic for sorting icons in data source
http://somup.com/crf3IAFbsV
=> OD-468 [Feature] Set default sorting orders to the data source list

css/interface.css, js/interface.js, js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-912
=> ID-912 [Fix] Avoid creating multiple table instances when opening data sources

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1027
=> ID-1027 [Fix] Scroll user to the selected cell when using the "Find" feature

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1027?focusedCommentId=18687
Follows https://github.com/Fliplet/fliplet-widget-data-source/pull/141
=> ID-1027 [Fix] Avoid focussing on search field after a change is made

css/interface.css, js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1029
=> ID-1029 [Feat] Improve sort UI to make the feature more discoverable

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-1040
Also fixes https://weboo.atlassian.net/browse/OD-509
=> ID-1040 [Fix] Show versions list after switching away and back to the list

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1043
=> ID-1043 [Fix] Ensures table is full rendered after sorting

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1043
Follows https://github.com/Fliplet/fliplet-widget-data-source/pull/147
=> ID-1043 [Fix] Add more delay for render to complete before forcing a render patch

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1043
Follows https://github.com/Fliplet/fliplet-widget-data-source/pull/147
=> ID-1043 [Fix] Adjusts render after render is completed

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-1043
https://github.com/handsontable/handsontable/pull/5134 became available in 4.0.0.
Follows https://github.com/Fliplet/fliplet-widget-data-source/pull/147
=> ID-1043 [Fix] Changes bug fix for partial sort renders to use official bug fix

interface.html, js/interface.js, js/interface.templates.js
> Specify columns that should never be readable (or writeable, depending on the operation) to users when this rule is matched.
=> ID-1161 [Chore] Updates copy for excluded columns following backend updates

js/interface.js
DS security rule UI does not update correctly
=> OD-534 [FIX] Force update of the Data Source security rules

js/interface.js, js/interface.templates.js, templates/versions.interface.hbs
=> [Chore] Improvements to displayed date

css/interface.css
Ref. https://weboo.atlassian.net/browse/ID-1278
=> ID-1278 [Fix] Keep user's vertical scroll position when scrolling horizontally

css/interface.css
Ref. https://weboo.atlassian.net/browse/ID-1278
=> ID-1278 [Fix] Adjust cell width and height to improve usability

js/spreadsheet.js
@sofiiakvasnevska @inna-bieshulia
OD-508 https://weboo.atlassian.net/browse/OD-508
Fixed to saving size after moving columns. The column is now resized after being moved.
https://storyxpress.co/video/krqjvs9ehxp7ssjwe
@upplabs-alex-levchenko @S-Volodymyr @skrupnyk
=> OD-508 [FIX] Fixed to saving size after moving columns

js/interface.js, js/spreadsheet.js
@sofiiakvasnevska @inna-bieshulia
OD-610 https://weboo.atlassian.net/browse/OD-610
**Problem:** 
1. Request for all data sources was using a URL for current app ones.
2. Class "hidden" was not removing from the $noResults block with empty "Trash".
3. List of all data sources was used for "Trash" data sources
**Solution:**
1. Added logic to split all and app-specific data source requests.
2. Removing "hidden" class if "Trash" is empty
3. Added check for 'deletedAt' key to prevent showing alive data sources in "Trash"
https://storyxpress.co/video/ksyhkp654zr79tbxc
=> OD-610 [FIX] Fixed display of the data sources in the Trash view

interface.html, js/interface.js
=> ID-1422 added info message for system managed data sources

interface.html, js/interface.js
=> ID-1422 [Chore] Disallow editing rules for managed data sources

js/interface.js, js/interface.templates.js
@romanyosyfiv @inna-bieshulia
OD-771 https://weboo.atlassian.net/browse/OD-771
=> OD-771 [Fix] Fixed DS overlay loading through the DS provider

js/history.js, js/interface.js, js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-2158
=> ID-2158 [Fix] Update table data with inserted entry IDs

js/interface.js
Product areas affected
Fliplet Widget Data Source, interface.js
What does this PR do?
DS manager can load 250k+ entries now
JIRA ticket
[JIRA ticket](https://weboo.atlassian.net/browse/XOR-61)
Result
[Screen Recordings](https://api.media.atlassian.com/file/92a35117-6ed8-4c95-b5c5-cdc4dd3ed5cb/artifact/video_1280.mp4/binary?client=435f5956-a841-4ea9-80ca-d94a2672bba6&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI0MzVmNTk1Ni1hODQxLTRlYTktODBjYS1kOTRhMjY3MmJiYTYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmMwMDg4MTAxLWRjNWItNDM0Zi04N2IxLTczOTI3Nzk3OTNiZSI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTozNzFmOWIyOC0xYTRhLTQ4ZTYtODdjNi0yN2M0YjI2ZDlmNmQiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6OTJhMzUxMTctNmVkOC00Yzk1LWI1YzUtY2RjNGRkM2VkNWNiIjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOjU1YWEw …
=> XOR-61 [FIX] DS manager cannot load entries with 250K records.

js/interface.js
- Reimplement changes incorrectly reverted in https://github.com/Fliplet/fliplet-widget-data-source/pull/116
=> [Fix] Reimplements changes done in OD-100 and reverted by OD-65

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2409
Revert back to committing all entries (but keep all the refactoring) in order to unblock data source manager deployments.
=> ID-2409 [Fix] Commit all entries on save

js/interface.js, js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-2538
=> ID-2538 [Fix] Avoid stripping data when entering numbers into a column with an object

interface.html, js/interface.js, js/interface.templates.js, templates/accessRule.interface.hbs
- DS security Rules for data source
- New Include column feature added while adding DS security rules
- Include column feature added based on 'All Users','LoggedIn Users' and 'Specific Users' while creating Data source security rules
- Include/exclude radio button added 
- Include exclude tagline proper messages added as per READ,WRITE ,UPDATE and DELETE behavior
[XOR-280](https://weboo.atlassian.net/browse/XOR-280)
- UI screen
- Scenarios for
Specific Users
[XOR-Test-280-ALL.webm](https://user-images.githubusercontent.com/107605720/186910163-708617ac-6e5c-4d71-b4af-4914bdda087a.webm)
LoggedIn Users
[XOR-Test-280-Log.webm](https://user-images.githubusercontent.com/107605720/186910183-ecdf4bd2-7fb2-45bd-93c3-701c79d53c6f.webm)
All Users …
=> XOR-280 [FEAT] Add support for configuring column inclusion and exclusion in security rules

js/interface.js
Screen -> App Data -> Data Sources -> Security Rules -> Reorder Rules/Edit Rules/Toggle Rules -> Save & Apply
Implemented fix so that visibility issue of Save & Apply button is resolved without saving rules.
[JIRA](https://weboo.atlassian.net/browse/XOR-406)
[XOR-406+.webm](https://user-images.githubusercontent.com/108272606/188655887-0e514b1a-8511-407c-a28d-af4cfe97a539.webm)
none
none
none
none
=> XOR-406 [Fix] Ensure "Save & Apply" button is hidden until changes are made to a data source

css/interface.css
Ref. https://weboo.atlassian.net/browse/ID-2549
=> ID-2549 [Fix] Ensures the first data row is editable

js/interface.js
Screen -> App Data -> Create / Edit Datasource -> Security Rules -> Create / Edit Security Rules
Implemented feature to trim spaces in DS Security rules values
[JIRA](https://weboo.atlassian.net/browse/XOR-485)
[XOR-Test-485.webm](https://user-images.githubusercontent.com/108272606/190193068-d08c2c84-798c-400a-ac97-2de921f38bc1.webm)
none
none
none
none
=> XOR-485 [Feat] Ensure DS security rules spaces trimmed

css/interface.css
Studio->App Data->ALL
Studio->App Data->Trash
Fixed the issue of data source name with a long title 
JIRA ticket
[JIRA ticket](https://weboo.atlassian.net/browse/XOR-422)
**Result**
Checklist
**None**
None
None
None
=> XOR-495 [FIX] Ensure showing the data source name with a long title 

js/interface.js
App Data
Added condition for loading data sources in app data properly.
[click here](https://weboo.atlassian.net/browse/XOR-566)
**Result**
**Checklist**
None
None
None
None
=> XOR-566 [FIX] Ensure data sources loading properly in app data

js/interface.js
The ES6 syntax is preventing ESLint from working as it's catching a series of syntax errors that aren't supported by ES5.
=> Removes ES6 syntax to reactivate ESLint

js/interface.js
App Setting ->API Tokens->Edit Token UI
Fixed the edit token UI issue while clicking on manage security rule button after click on the specific-token-filter button if the accessRule is null
[JIRA ticket](https://weboo.atlassian.net/browse/XOR-203)
**Result**
**Checklist**
None
None
None
None
=> XOR-203 [FIX] Ensure app edit token UI not broken

css/interface.css, interface.html, js/interface.js
Studio -> App Data -> Open DS -> Message for live app DS changes
Implemented functionality to show warning message if app is live and changes made to DS
[click here](https://weboo.atlassian.net/browse/XOR-276)
**Result**
**Checklist**
None
None
None
Author concerns
None
=> XOR-276 [FEAT] Warn users of live data changes when editing data sources via DSM

js/interface.js
- Datasource write/update operation on data restriction the basis of DS security rule.
- Spilt exclude columns list with ', ' as it contains space between columns names pass from UI for exclude columns
[XOR-543](https://weboo.atlassian.net/browse/XOR-543)
Relevant sample input/output, screenshots or screen recordings.
https://user-images.githubusercontent.com/107605720/196167191-941905e6-563e-4a43-ae79-05281c019f86.mp4
https://user-images.githubusercontent.com/107605720/196167283-cff29b6f-3a10-4862-a49d-06dbf3f7cb42.mp4
=> XOR-543 [FIX] write/update data in the columns that are excluded by a DS security rule issue fixed.

interface.html, js/interface.js
App settings->API token -> Edit Token -> Manage Security Rules -> change Selected ID Token (token ID issue)
App settings->API token -> Edit Token -> Manage Security Rules (glitch issue)
Implemented solution for DS glitches and token ID change issues
[JIRA ticket](https://weboo.atlassian.net/browse/XOR-203)
**Result**
https://user-images.githubusercontent.com/108272606/195558854-19c1c6b6-b581-4a63-a92c-8e51e182cfac.mp4
**Checklist**
None
None
None
None
=> XOR-203 [FIX] Ensure DS glitches and token ID change issue resolved

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2787
**Before**
**After**
=> ID-2787 [Feat] Exclude conversation data sources

interface.html
Ref. https://github.com/Fliplet/fliplet-api/pull/5604
=> [Maintenance] Updates information based on latest DS versioning changes

css/interface.css
Ref. https://weboo.atlassian.net/browse/ID-2791
=> ID-2791 [Fix] Fix issue with positioning of editing cells

js/interface.js, js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-2415
Should avoid the following issues from occurring:
- https://weboo.atlassian.net/browse/ID-2409
- https://weboo.atlassian.net/browse/ID-2410
=> ID-2415 [Feat] Selectively commit changes to the data source

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-2821
=> ID-2821 [Fix] Do not remove double quotes in strings

interface.html, js/interface.js, js/interface.templates.js, templates/accessRule.interface.hbs
- https://weboo.atlassian.net/browse/ID-1234
- https://weboo.atlassian.net/browse/ID-2814
---
Supersedes https://github.com/Fliplet/fliplet-widget-data-source/pull/157
=> ID-1234 ID-2814 [Feat] UI for custom access rules

interface.html, js/interface.js, js/interface.templates.js, js/spreadsheet.js, templates/accessRule.interface.hbs
=> Release to production

js/interface.js, js/interface.templates.js, templates/apiTokenList.interface.hbs
requires https://github.com/Fliplet/fliplet-api/pull/5629
=> ID-2830 [Chore] Fetch api tokens from all apps to populate tokens dropdown

js/spreadsheet.js
Ref. https://weboo.atlassian.net/browse/ID-2826
=> ID-2826 [Fix] Do not process number strings into numbers

js/interface.js, js/interface.templates.js, js/spreadsheet.js
Studio -> App Data -> DS -> Create / Edit DS
Implemented code for hide message on DS dialog when error come.
[click here](https://weboo.atlassian.net/browse/XOR-848)
**Result**
https://user-images.githubusercontent.com/108272606/213679441-c3a829b4-45cc-4802-8a8b-276f3a12e46a.mp4
**Checklist**
None
None
None
None
=> XOR-848 [FIX] Ensure DS message hidden for error scenarios

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2897
=> ID-2897 [Fix] Managing security rule saving states and errors

js/interface.js, js/interface.templates.js
- Check if error response is handled
https://weboo.atlassian.net/browse/GD-450
https://github.com/Fliplet/fliplet-studio/pull/7543
=> GD-450 [Feat] Check if error response is handled

js/interface.js, js/interface.templates.js
https://github.com/Fliplet/fliplet-widget-data-source/assets/128052346/e86f84be-758a-4f9a-9c5c-e21cbd41a2a6
=> ID-3560 [FIX] Reset all the existing security rules after deleting specific token rule

js/interface.js
https://weboo.atlassian.net/browse/ID-4139
=> ID-4139 [fix]: saving reordered table

js/spreadsheet.js
https://weboo.atlassian.net/browse/ID-4230
https://github.com/Fliplet/fliplet-widget-data-source/assets/144125903/d570d863-f96d-40fb-ad63-2a1e4af8177e
=> fix(ID-4230): column sorting limited to ASC and DESC, removed going back to undefined sorting

js/interface.js
https://weboo.atlassian.net/browse/ID-4264
=> fix(ID-4264): fixed updating DS order definition when column was removed or renamed

js/columnsTracking.js, js/interface.js, js/spreadsheet.js
https://weboo.atlassian.net/browse/ID-4264
=> ID-4264 [fix] handle sorting by added, renamed and removed columns

js/columnsTracking.js, js/interface.js, js/spreadsheet.js
Reverts Fliplet/fliplet-widget-data-source#232 due to QA fail.
=> Revert "ID-4264 [fix] handle sorting by added, renamed and removed columns"

css/interface.css
https://weboo.atlassian.net/browse/PS-116
=> PS-116 [hotfix] dsm rows height

css/interface.css
Fliplet Widget Data Source
Ensures Data Source wrapping text  correctly
[PS-772](https://weboo.atlassian.net/browse/PS-772)
[PS-711](https://weboo.atlassian.net/browse/PS-711)
[PS-772]: https://weboo.atlassian.net/browse/PS-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PS-711]: https://weboo.atlassian.net/browse/PS-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-772 [FIX] Ensures Data Source wrapping text  correctly

css/interface.css
Reverts Fliplet/fliplet-widget-data-source#239 due to QA fail
=> Revert "PS-772 [FIX] Ensures Data Source wrapping text  correctly"

css/interface.css
Fliplet Widget Data Source
Ensures Data Source wrapping text  correctly
[PS-772](https://weboo.atlassian.net/browse/PS-772)
[PS-711](https://weboo.atlassian.net/browse/PS-711)
[PS-772]: https://weboo.atlassian.net/browse/PS-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PS-711]: https://weboo.atlassian.net/browse/PS-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix/PS-772:  Ensures Data Source wrapping text  correctly
